# Generated by Django 4.2.5 on 2023-09-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_companies_created_at_companies_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employ_comp_id', to='home.companies'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='company_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equip_comp_id', to='home.companies'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='employee_id',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='equip_employ_id', to='home.employees'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
